### ISSUE TITLE
where can i get the demo applications described in kernel rapidio/rio_cm ~

### ISSUE THREAD

**Issue by fafactx** [RapidIO/kernel-rapidio#24]
Thanks for you attitions.
I have a questions about message(mbox) apps demo in kernel doc .
My question is can tell me where I can get the userspace test demo discribed in linux/rio_cm.rst at master · torvalds/linux · GitHub 

Messaging API library and applications that use this device driver are available from RapidIO.org.
https://github.com/torvalds/linux/blob/master/Documentation/driver-api/rapidio/rio_cm.rst#5-user-space-applications-and-api-library
it means i can get applications demo in rapidio.org github ? I try but failed.

Thanks very much ~.

**Comment by abou9** [comment]
The code samples are located in kernel-rapidio/libmport/samples directory. See rio_test_server.c and rio_test_client.c.

Regards,

Alex

**Comment by abou9** [comment]
https://github.com/RapidIO/kernel-rapidio/tree/master/libmport/samples
